### ISSUE TITLE
ARM image need to be upgraded for new API

### ISSUE THREAD

**Issue by pilip87** [virtualzone/landroid-bridge#54]
But as @mhaack already mentioned: the arm image was last udated 11 month ago and lacks the fix for the API change. Thus, ATM you get rid of the `exec format error`, which is replaced by the `Unhandled exception: SyntaxError: Unexpected token N in JSON at position 0` error. ;-)

So, could someone please update the ARM image?

_Originally posted by @derandiunddasbo in https://github.com/weweave/landroid-bridge/issues/42#issuecomment-486765600_

**Comment by lukicsl** [comment]
Could anybody please also look at reducing the size of the image x86_64 is 63MB the arm image 285MB.

**Comment by lukicsl** [comment]
@pilip87 for the moment you could use my version [https://hub.docker.com/r/lukics/landroid](url) (105MB). I managed to create a multistage build and preparing a PR.

**Comment by virtualzone** [comment]
I've updated the ARM docker image - should work now.

**Comment by CaCu15** [comment]
I still have the problem with the RPI image: Keep getting the following error in the container logs: 

standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by derandiunddasbo** [comment]
Are you sure, you're running the image with the correct tag? It has to be `weweave/landroid-bridge:arm32v7`. Not `latest` or without any tag.

Please provide the output of `docker image ls`.

**Comment by CaCu15** [comment]
Hello derandiunddasbo,
the image weweave/landroid-bridge:arm32v7 is working for me, but the image from this repe (virtualzone/landroid-bridge) with the same tag does still produce the same error. Not a big issue, I switched to the working image, but I would prefer to switch back to using the original image from virtualzone/landroid-bridge.

**Comment by pilip87** [comment]
still not working for me.
This my docker-compose:

  landroid-bridge:
    image: weweave/landroid-bridge:arm32v7
    restart: "always"
    volumes:
      - /docker/landroid-bridge/config.json:/usr/src/app/config.json
    ports:
      - 3000:3000
    links:
      - mosquito


This the log:
sudo docker-compose up  landroid-bridge
mosquito is up-to-date
Creating docker_landroid-bridge_1
Attaching to docker_landroid-bridge_1
landroid-bridge_1  | [2019-06-13T12:49:56.642] [INFO] server.ts - Starting Landroid Bridge...
landroid-bridge_1  | [2019-06-13T12:49:56.654] [INFO] server.ts - Setting port to 3000...
landroid-bridge_1  | [2019-06-13T12:49:56.886] [INFO] Mqtt - Connecting to MQTT Broker...
landroid-bridge_1  | [2019-06-13T12:49:56.935] [INFO] App - Adding static files path /usr/src/app/www
landroid-bridge_1  | [2019-06-13T12:49:56.937] [INFO] Scheduler - Skipping scheduler initialization (not enabled)
landroid-bridge_1  | [2019-06-13T12:49:56.953] [INFO] LandroidS - Initializing Landroid Cloud Service...
landroid-bridge_1  | [2019-06-13T12:49:56.959] [WARN] IoBrokerAdapter - landroid-cloud-2.js will be replaced in next version by mqttCloud.js and worxConfig.js. Reason: better handling of models and mqttCloud supports more brands by a diffent config see also: https://www.npmjs.com/package/iobroker.kress
landroid-bridge_1  | [2019-06-13T12:49:57.157] [INFO] Mqtt - Successfully connected to MQTT Broker!
landroid-bridge_1  | [2019-06-13T12:49:57.356] [ERROR] App - Unhandled exception: SyntaxError: Unexpected token N in JSON at position 0
landroid-bridge_1  | [2019-06-13T12:50:56.993] [INFO] LandroidS - Could not finish initialization, retrying...
landroid-bridge_1  | [2019-06-13T12:50:56.995] [WARN] IoBrokerAdapter - landroid-cloud-2.js will be replaced in next version by mqttCloud.js and worxConfig.js. Reason: better handling of models and mqttCloud supports more brands by a diffent config see also: https://www.npmjs.com/package/iobroker.kress
landroid-bridge_1  | [2019-06-13T12:50:57.274] [ERROR] App - Unhandled exception: SyntaxError: Unexpected token N in JSON at position 0


Tell me if you need something more to help me!
Thank you

**Comment by derandiunddasbo** [comment]
> ut the image from this repo (virtualzone/landroid-bridge) with the same tag does still produce the same error

Sorry, didn't realize, that this is yet another landroid-bridge repo. :-)

**Comment by pilip87** [comment]
using virtualzone/landroid-bridge:arm32v7 instead I get:
sudo docker-compose up landroid-bridge
mosquito is up-to-date
Creating docker_landroid-bridge_1
Attaching to docker_landroid-bridge_1
landroid-bridge_1  | standard_init_linux.go:190: exec user process caused "exec format error"
docker_landroid-bridge_1 exited with code 1

Thanks

**Comment by robissm** [comment]
I get same error as pilip87 on RPI3B+ and using virtualzone/landroid-bridge:arm32v7
I have trie to build from docker file, but npm fails, so does the build.

**Comment by derandiunddasbo** [comment]
Well,I don't know, if this repo is still maintained. As it was last updated more than a year ago, I suspect it'll work even if it would provide a working ARM image, because of the recent API changes by Worx. You may use the docker image from weweave. I'm not using it anymore, because I switched to a x64 platform as my docker host some months ago, but as far as I remember, the mentioned API changes were incorporated in weweave's version: 

weweave/landroid-bridge:arm32v7
